[[redirects]]
force = true
from = "/custom-website-design/"
status = "301"
to = "/services/small-business-website-design/"
[[redirects]]
force = true
from = "/customers/*"
status = 301
to = "/portfolio"
[[redirects]]
force = true
from = "/free-site-setup/*"
status = 301
to = "/contact"
[[redirects]]
force = true
from = "/real-estate-websites/"
status = 301
to = "/agent-idx-websites"
[[redirects]]
force = true
from = "/projects/*"
status = 301
to = "/portfolio"
[[redirects]]
force = true
from = "/pricing/"
status = 301
to = "/faq"
[[redirects]]
force = true
from = "/jamstack-website-design/"
status = 301
to = "/custom-website-design"
