---
label: Services
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: description
  type: text
  config:
    required: false
  label: Description
- name: featured
  type: boolean
  label: Featured
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: intro
  type: field_group
  config: {}
  fields:
  - name: heading
    type: text
    config:
      required: false
    label: Heading
  - name: body
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: Body
  label: Intro
- name: banner
  type: field_group
  config: {}
  fields:
  - name: heading
    type: text
    config:
      required: false
    label: Heading
  - name: body
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: Body
  label: Banner
- name: second_intro
  type: field_group
  config: {}
  fields:
  - name: heading
    type: text
    config:
      required: false
    label: Heading
  - name: body
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: Body
  label: Second Intro
- name: search_engine_optimization
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Search Engine Optimization
pages:
- content/services/custom-website-design.md
- content/services/responsive-web-design.md
- content/services/websites-with-ssl-certificates.md
